### ISSUE TITLE
有使用文档么

### ISSUE THREAD

**Issue by fancey** [pojol/gobot#28]
如何使用哈

**Comment by pojol** [comment]
文档的地址在 https://pojol.github.io/gobot/#/ 这里(可能需要一些🪜类的工具
使用的话可以参考这个视频 https://www.bilibili.com/video/BV1sS4y1z7Dg/?vd_source=7c2dfd750914fd5f8a9811b19f0bf447

虽然演示的版本较老，但使用方式是差不多的
